title: Marketechnic
description: Technical Marketing Consulting by an Industry Expert
theme: jekyll-theme-minimal

## Navigation

- [Home](index.md)
- [About](about.md)
- [Contact](contact.md)

# Welcome to Marketechnic

![Marketechnic Logo](MARKETECHNIC.gif)
